CREATE DATABASE PRESENTATION
USE PRESENTATION

CREATE LOGIN FAIZAN WITH PASSWORD = 'FAIZAN2025'
CREATE USER FAIZAN FROM LOGIN FAIZAN

GRANT SELECT, INSERT ON STUDENT TO FAIZAN

REVOKE SELECT, INSERT ON STUDENT FROM FAIZAN

SELECT * FROM STUDENT

EXECUTE AS USER = 'FAIZAN'


DROP USER FAIZAN
DROP LOGIN FAIZAN
DROP TABLE STUDENT

SELECT SYSTEM_USER
REVERT